# Generated by Django 3.0.4 on 2020-04-01 21:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191028_2308'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ConnectionSubtype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.ConnectionType')),
            ],
        ),
        migrations.CreateModel(
            name='Connections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('since', models.DateTimeField(verbose_name='since')),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections_connect', to=settings.AUTH_USER_MODEL)),
                ('connection_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.ConnectionType')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
