# Generated by Django 3.0.4 on 2020-04-01 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_connections_connectionsubtype_connectiontype'),
    ]

    operations = [
        migrations.AddField(
            model_name='connections',
            name='connection_subtype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.ConnectionSubtype'),
        ),
    ]
