# Generated by Django 3.0.4 on 2020-04-02 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_connections_connection_subtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connections',
            name='connection_subtype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.ConnectionSubtype'),
        ),
    ]
