# Generated by Django 3.0.4 on 2020-04-07 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200402_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='connections',
            name='pendent',
            field=models.BooleanField(default=True),
        ),
    ]
